### ISSUE TITLE
How to get demo example?

### ISSUE THREAD

**Issue by mohammedhazim** [mgcrea/react-native-dnd#7] opened 2023-08-24 13:19 UTC
Hello, can you please submit example about demo app like the image!

Because there is no clear example to do that.

![image](https://github.com/mgcrea/react-native-dnd/assets/135952445/1ab750bc-c3e7-41c1-87aa-cc4e0450edbb)

**Comment by mgcrea** [comment] 2023-09-12 15:02
Duplicate of #1, source code is coming.

**Closed by mgcrea** 2023-09-12 15:02 UTC
